image: nkx1231/root6-geant4-garfield:0.2

stages:
  - pre-build
  - build
  - loadRESTLibs
  - generate
  - process
  - drawing
  - deploy

before_script:
  - export USER="test"

clang-format:
    stage: pre-build
    script:
        - cd ${CI_PROJECT_DIR}/
        - ./macros/pipeline/clangformattest.sh
    before_script:
        - apt-get update -y && apt-get upgrade -y
        - apt-get install -y cmake git findutils clang-format

validateCode:
    stage: pre-build
    script:
        - python ${CI_PROJECT_DIR}/macros/pipeline/validateProcesses.py ${CI_PROJECT_DIR}/source/processes/

build:
  type: build
  script:
    - mkdir /tmp/rest && cd /tmp/rest
    - rm -rf ${CI_PROJECT_DIR}/install
    - cmake ${CI_PROJECT_DIR} -DREST_WELCOME=OFF -DREST_GARFIELD=ON -DREST_G4=ON -DINSTALL_PREFIX=${CI_PROJECT_DIR}/install
    - make install -j2
    - . ${CI_PROJECT_DIR}/install/thisREST.sh
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/install
    expire_in: 1 day

loadRESTLibs:
  type: loadRESTLibs
  script:
    - . ${CI_PROJECT_DIR}/install/thisREST.sh
    - root -b -q ${CI_PROJECT_DIR}/install/macros/pipeline/loadLibraries.C

testrestG4:
  type: generate
  script:
    - . ${CI_PROJECT_DIR}/install/thisREST.sh
    - cd ${CI_PROJECT_DIR}/install/examples/01.NLDBD-PandaX-III/
    - echo 1 > ${CI_PROJECT_DIR}/install/runNumber
    - restG4 NLDBD.rml
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/install/examples/01.NLDBD-PandaX-III/Run00001_NLDBD_Test.root
    expire_in: 1 day

testMeta:
  type: generate
  script:
    - . ${CI_PROJECT_DIR}/install/thisREST.sh
    - cd ${CI_PROJECT_DIR}/install/examples
    - restManager --c saveMetadataFile.rml --o meta.root
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/install/examples/meta.root
    expire_in: 1 day


testProcessTREX: 
  type: process
  script:
    - . ${CI_PROJECT_DIR}/install/thisREST.sh
    - cd ${CI_PROJECT_DIR}/install/macros/pipeline/trex
    - restManager --c 01_raw.rml --f data.aqs
    - restManager --c 02_signal.rml --f RawData.root
    - restManager --c 03_hits.rml --f Signals.root
    - restRoot -b -q MakeBasicTree.C
    - rm RawData.root
    - rm Signals.root
    - rm Hits.root
    - root -b -q ${CI_PROJECT_DIR}/install/macros/pipeline/trex/ValidateTrees.C
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/install/macros/pipeline/trex/results.root
    expire_in: 1 week

testProcessElectronics: 
  type: process
  script:
    - . ${CI_PROJECT_DIR}/install/thisREST.sh
    - cd ${CI_PROJECT_DIR}/install/examples
    - restManager --c electronicsSimu.rml --i "01.NLDBD-PandaX-III/Run00001_NLDBD_Test.root" --o electronics.root
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/install/examples/electronics.root
    expire_in: 1 week

testProcessG4Ana: 
  type: process
  script:
    - . ${CI_PROJECT_DIR}/install/thisREST.sh
    - cd ${CI_PROJECT_DIR}/install/examples
    - restManager --c g4Analysis.rml --i "01.NLDBD-PandaX-III/Run00001_NLDBD_Test.root" --o g4Ana.root
    - restManager --c g4ToHits.rml --i g4Ana.root --o g4Hits.root
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/install/examples/g4Ana.root
      - ${CI_PROJECT_DIR}/install/examples/g4Hits.root
    expire_in: 1 week

testDrawing: 
  type: drawing
  script:
    - . ${CI_PROJECT_DIR}/install/thisREST.sh
    - cd ${CI_PROJECT_DIR}/install/examples
    - restManager --c plotAnaSpectrum.rml --i electronics.root --o spec.root --p spec.pdf
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/install/examples/spec.pdf
    expire_in: 1 week

deploy:
  type: deploy
  only:
    - tags
  script:
    - . ${CI_PROJECT_DIR}/install/thisREST.sh
    - rest-config --welcome
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/install
