image: nkx1231/root6-geant4-garfield:0.4

stages:
  - pre-build
  - build
  - restRoot
  - restManager_generate
  - restManager_process
  - deploy

before_script:
  - export USER="test"
    # We redefine the HOME
  - export HOME=${CI_PROJECT_DIR}/install/
  - if [ -d $HOME/.rest ]; then rm -Rf $HOME/.rest; fi

clang-format:
    stage: pre-build
    script:
        - cd ${CI_PROJECT_DIR}/
        - ./scripts/pipeline/clangformattest.sh
    except:
        variables:
            - $CI_SERVER_HOST
    only:
        variables:
            - $CRONJOB

validateCode:
    stage: pre-build
    script:
        - python ${CI_PROJECT_DIR}/scripts/pipeline/validateProcesses.py ${CI_PROJECT_DIR}/source/processes/
    except:
        variables:
            - $CRONJOB

build:
  type: build
  script:
    - mkdir /tmp/rest && cd /tmp/rest
    - rm -rf ${CI_PROJECT_DIR}/install
    - cmake ${CI_PROJECT_DIR} -DREST_WELCOME=OFF -DREST_GARFIELD=ON -DREST_G4=ON -DINSTALL_PREFIX=${CI_PROJECT_DIR}/install
    - make install -j2
    - . ${CI_PROJECT_DIR}/install/thisREST.sh
  except:
      variables:
        - $CRONJOB
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/install
    expire_in: 1 day



loadRESTLibs:
  type: restRoot
  script:
    - . ${CI_PROJECT_DIR}/install/thisREST.sh
    - root -b -q ${CI_PROJECT_DIR}/scripts/pipeline/loadLibraries.C
    - restRoot -b -q
  except:
      variables:
        - $CRONJOB

gas:
  type: restRoot 
  script:
    - . ${CI_PROJECT_DIR}/install/thisREST.sh
    - cd ${CI_PROJECT_DIR}/scripts/pipeline
    - restRoot -b -q ValidateGas.C




testMeta:
  type: restManager_generate
  script:
    - . ${CI_PROJECT_DIR}/install/thisREST.sh
    - cd ${CI_PROJECT_DIR}/install/examples
    - restManager --c saveMetadataFile.rml --o meta.root
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/install/examples/meta.root
    expire_in: 1 day
  except:
      variables:
        - $CRONJOB




testProcessTREX: 
  type: restManager_process
  script:
    - . ${CI_PROJECT_DIR}/install/thisREST.sh
    - cd ${CI_PROJECT_DIR}/scripts/pipeline/trex
    - restManager --c 01_raw.rml --f data.aqs
    - restManager --c 02_signal.rml --f RawData.root
    - restManager --c 03_hits.rml --f Signals.root
    - restRoot -b -q MakeBasicTree.C
    - rm RawData.root
    - rm Signals.root
    - rm Hits.root
    - root -b -q ${CI_PROJECT_DIR}/scripts/pipeline/trex/ValidateTrees.C
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/scripts/pipeline/trex/results.root
    expire_in: 1 week
  except:
      variables:
        - $CRONJOB

testProcessPandaX: 
  type: restManager_process
  script:
    - . ${CI_PROJECT_DIR}/install/thisREST.sh
    - cd ${CI_PROJECT_DIR}/scripts/pipeline/pandaxiii
    - restG4 Xe136bb0n.rml
    - restRoot -b -q ValidateG4.C'("Xe136bb0n_n2E06.root")'
    - restManager --c AllProcesses.rml --i Xe136bb0n_n2E06.root --o Xe136bb0n_Process.root --e 1000 --j 1
    - restRoot -b -q ValidateTrack.C'("Xe136bb0n_Process.root")'
    - restManager --c plots.rml --i Xe136bb0n_Process.root
    - restRoot -b -q ValidatePlot.C'("trackParameter.png")'
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/scripts/pipeline/pandaxiii/trackParameter.pdf
    expire_in: 1 week
  except:
      variables:
        - $CRONJOB


deploy:
  type: deploy
  only:
    - tags
  script:
    - . ${CI_PROJECT_DIR}/install/thisREST.sh
    - rest-config --welcome
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/install
  except:
      variables:
        - $CRONJOB
