image: lobis/root:6.16.00

stages:
  - build

build:
  type: build
  script:
    - mkdir /tmp/rest && cd /tmp/rest
    - cmake ${CI_PROJECT_DIR} -DREST_WELCOME=OFF -DREST_GARFIELD=OFF -DINSTALL_PREFIX=/opt/rest
    - make install
    - source /opt/rest/thisREST.sh
    - rest-config --version