image: nkx1231/root6-geant4-garfield:0.2

stages:
  - build
  - opening
  - generate
  - process1
  - process2
  - drawing
  - deploy

before_script:
  - export USER="test"

build:
  type: build
  script:
    - mkdir /tmp/rest && cd /tmp/rest
    - rm -rf ${CI_PROJECT_DIR}/install
    - cmake ${CI_PROJECT_DIR} -DREST_WELCOME=OFF -DREST_GARFIELD=ON -DREST_G4=ON -DINSTALL_PREFIX=${CI_PROJECT_DIR}/install
    - make install -j2
    - . ${CI_PROJECT_DIR}/install/thisREST.sh
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/install
    expire_in: 1 day
     


testOpeningOld:
  type: opening
  script:
    - . ${CI_PROJECT_DIR}/install/thisREST.sh



testrestG4:
  type: generate
  script:
    - . ${CI_PROJECT_DIR}/install/thisREST.sh
    - cd ${CI_PROJECT_DIR}/install/examples/01.NLDBD-PandaX-III/
    - echo 1 > ${CI_PROJECT_DIR}/install/runNumber
    - restG4 NLDBD.rml
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/install/examples/01.NLDBD-PandaX-III/Run00001_NLDBD_Test.root
    expire_in: 1 day

testMeta:
  type: generate
  script:
    - . ${CI_PROJECT_DIR}/install/thisREST.sh
    - cd ${CI_PROJECT_DIR}/install/examples
    - restManager --c saveMetadataFile.rml --o meta.root
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/install/examples/meta.root
    expire_in: 1 day
      


testProcessRaw: 
  type: process1
  script:
    - . ${CI_PROJECT_DIR}/install/thisREST.sh
    - cd ${CI_PROJECT_DIR}/install/examples
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/install/examples/rawAna.root
    expire_in: 1 week

testProcessElectronics: 
  type: process1
  script:
    - . ${CI_PROJECT_DIR}/install/thisREST.sh
    - cd ${CI_PROJECT_DIR}/install/examples
    - restManager --c electronicsSimu.rml --i "01.NLDBD-PandaX-III/Run00001_NLDBD_Test.root" --o electronics.root
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/install/examples/electronics.root
    expire_in: 1 week

testProcessG4Ana: 
  type: process1
  script:
    - . ${CI_PROJECT_DIR}/install/thisREST.sh
    - cd ${CI_PROJECT_DIR}/install/examples
    - restManager --c g4Analysis.rml --i "01.NLDBD-PandaX-III/Run00001_NLDBD_Test.root" --o g4Ana.root
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/install/examples/g4Ana.root
    expire_in: 1 week



testProcessRest: 
  type: process2
  script:
    - . ${CI_PROJECT_DIR}/install/thisREST.sh
    - cd ${CI_PROJECT_DIR}/install/examples
    - restManager --c g4ToHits.rml --i g4Ana.root --o g4Hits.root
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/install/examples/g4Hits.root
    expire_in: 1 week



testDrawing: 
  type: drawing
  script:
    - . ${CI_PROJECT_DIR}/install/thisREST.sh
    - cd ${CI_PROJECT_DIR}/install/examples
    - restManager --c g4ToHits.rml --i g4Ana.root --o g4Hits.root
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/install/examples/g4Hits.root
    expire_in: 1 week



deploy:
  type: deploy
  only:
    - tags
  script:
    - . ${CI_PROJECT_DIR}/install/thisREST.sh
    - rest-config --welcome
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/install