image: nkx1231/root6-geant4-garfield:0.1

stages:
  - build
  - testMetarestG4
  - testProcess



before_script:
  - . /root/installgarfield.sh

build:
  type: build
  script:
    - mkdir /tmp/rest && cd /tmp/rest
    - cmake ${CI_PROJECT_DIR} -DREST_WELCOME=OFF -DREST_GARFIELD=ON -DINSTALL_PREFIX=/builds/pandax-iii/REST_v2/install
    - make install
    - . /builds/pandax-iii/REST_v2/install/thisREST.sh
    - mkdir /tmp/restg4 && cd /tmp/restg4
    - cmake ${CI_PROJECT_DIR}/packages/restG4
    - make install
  artifacts:
    paths:
      - /builds/pandax-iii/REST_v2/install
      
testrestG4:
  type: testMetarestG4
  script:
    - . /builds/pandax-iii/REST_v2/install/thisREST.sh
    - cd /builds/pandax-iii/REST_v2/install/example/restG4template
    - restG4 restG4.rml
  artifacts:
    paths:
      - /builds/pandax-iii/REST_v2/install

testMeta:
  type: testMetarestG4
  script:
    - . /builds/pandax-iii/REST_v2/install/thisREST.sh
    - cd /builds/pandax-iii/REST_v2/install/example
    - restManager --c saveMetadataFile.rml --o meta.root
  artifacts:
    paths:
      - /builds/pandax-iii/REST_v2/install
      
testProcess:
  type: testProcess
  script:
    - export USER="test"
    - . /builds/pandax-iii/REST_v2/install/thisREST.sh
    - cd /builds/pandax-iii/REST_v2/install/example
    - restManager --c electronicsSimu.rml restG4template/example_output.root --o abc.root
  artifacts:
    paths:
      - /builds/pandax-iii/REST_v2/install