image: nkx1231/root6-geant4-garfield

types:
  - build

build:
  type: build
  script:
    - . /root/installgarfield.sh
    - mkdir /tmp/build
    - cd /tmp/build
    - cmake ${CI_PROJECT_DIR} -DREST_WELCOME=OFF -DREST_GARFIELD=ON
    - make
    - make install
